[build]
builder = "NIXPACKS"
buildCommand = "bun install && cd web && bun install && bun run build"

[deploy]
startCommand = "bun run db:push && bun run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
